### localhost
#mqtthost: 127.0.0.1
#mqttport: 1883
### hivemq
mqtthost: broker.hivemq.com
mqttport: 1883
# needs / in the end
spfx: _1451.1.6/
tomdop: D/
tomcop: C/
tomd0op: D0/
# Does not need / in the end
loc: OUC-LEC/2023/ncap0
locclient: OUC-LEC/2023/application0
